filter blank lines from `default_config`
Otherwise, they cause a cryptic parsing error along the lines of:

```
ERROR: Invalid config: Found invalid config 'kuma.default_settings':
```